name: CI

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]
    types:
      - opened
      - reopened
      - synchronize

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    container:
      image: valalang/lint

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        run: io.elementary.vala-lint -d .

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build docker images
        run: docker-compose build

      - name: Run tests
        run: docker-compose run test
